### ISSUE TITLE
Fireform doesn't work well in Firefox

### ISSUE THREAD

**Issue by jatindhankhar** [SFDevLabs/fireform#3]
I recently made a simple form for testing purposes and used the boilerplate code as given by fireform. 
Submission works well in Chrome but it doesn't work in firefox, instead query appends itself to the url like it is being made on the server serving the page and the data is not pushed the fireform

Here are screenshots 
# Chrome
![screenshot from 2015-01-19 21 18 11](https://cloud.githubusercontent.com/assets/2412081/5803046/c286cf86-a020-11e4-9a3b-9f1b8bdcc146.png)

# Firefox
![screenshot from 2015-01-19 21 18 23](https://cloud.githubusercontent.com/assets/2412081/5803057/dbc3302a-a020-11e4-86f2-8fd856167d07.png)

**Comment by jeffj** [comment]
This has been resolved in Firefox and IE from this commit:
https://github.com/SFDevLabs/fireform/commit/56100e2e78ba5c57c91120a2614b509e15936552


![screenshot 2015-01-19 16 31 25](https://cloud.githubusercontent.com/assets/237260/5810287/a8146f8c-9ff8-11e4-81b8-c86590855aaf.png)
![screenshot 2015-01-19 16 31 17](https://cloud.githubusercontent.com/assets/237260/5810289/a81ba824-9ff8-11e4-8a00-c62f1e90af13.png)
![screenshot 2015-01-19 16 31 12](https://cloud.githubusercontent.com/assets/237260/5810288/a817321c-9ff8-11e4-92ee-90a9674f6077.png)
